### ISSUE TITLE
Sonoff acts as access point all the time

### ISSUE THREAD

**Issue by hjgode** [arendst/Sonoff-MQTT-OTA-Arduino#1]
Is there any reason why Sonoff-MQTT acts always as an AP ESP_hex) instead of as Station only?

This will occupy one additional channel in the WLAN and possibly interfers with existing APs.

Possibly add Wifi.mode(STA).

**Comment by arendst** [comment]
Thanks for noticing. I had the problem too on other projects I moved to Arduino using ESP-12F but not on the sonoff. Did add your suggestion to wifi.ino which solves it.

**Comment by hjgode** [comment]
Thanks, the changes fixes the issue with the sonoff acting as AP all the time.
