### ISSUE TITLE
MQTT Message retention

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-MQTT-OTA-Arduino#104]
Hello,
Is the message retention flag working for everyone? I've set the MQTT_BUTTON_RETAIN to 1 in the user_config.h file. However, when a new client subscribes on MQTT, nothing is returned. Am I doing something wrong or is this potentially a bug?

**Comment by arendst** [comment]
Message retention set with command BUTTONRETAIN (user_config.h only works once initially as it is stored in flash) works in concert with BUTTONTOPIC only.

So to use it you'll have to define a MQTT topic for the button which triggers the relay using the MQTT broker. This can be the same topic as set with command TOPIC but it could also be something send from your home automation tool. 

The feature can be turned off by command BUTTONTOPIC 0
