### ISSUE TITLE
MQTT blocking connection attempt

### ISSUE THREAD

**Issue by jaime1988** [arendst/Sonoff-MQTT-OTA-Arduino#108]
Hi, first of all thanks for all your code and effort. 
It seems that when the device can not connect to the mqtt server, the button doesn't work correctly while the device is trying to connect. So if no correct mqtt is running, the device doesn't work correctly. Is there any possible solution?

**Comment by 0n3-70uch** [comment]
Hi, same result here. I think the problem also occurs if the device is not connected to a local wifi.

Greetings
Fabi

**Comment by arendst** [comment]
What is worse without power the whole thing is useless!

**Comment by 0n3-70uch** [comment]
Yes you are right... a Sonoff without Wifi is just a power killer ;). 

There is only a little problem, if there is no Wifi (defect router) or no MQTT Broker (offline)... But for that it is ok when the button response is a little bit delayed.

Thanks for your good statement... for me this topic is closed :).
