### ISSUE TITLE
Problems with flashing Sonoff Dual

### ISSUE THREAD

**Issue by thommycgn** [arendst/Sonoff-MQTT-OTA-Arduino#113]
Hello, 

I'm using the flashtool on Mac to copy the binary on Sonoff. It works fine with the sonoff but not with sonoff dual. 

______
python esptool.py -p /dev/tty.usbserial-A50285BI --baud 460800 write_flash --flash_size=detect 0 sonoff.ino.bin 

esptool.py v1.3-dev
Connecting...

A fatal error occurred: Failed to connect to ESP8266
____

Any idea what could be wrong? 
Is it right to connect the pins on the top side of the board?

**Comment by arendst** [comment]
See wiki. You might find programming the dual is challenging...
