### ISSUE TITLE
Extra GPIO for all Sonoff?

### ISSUE THREAD

**Issue by Reinhartd** [arendst/Sonoff-MQTT-OTA-Arduino#119]
Hello Theo!

can you make a switch to disable the serial communication (RxD + TxD), flashing is everyone over OTA.
Then we can use the gpio1 and gpio3 for other devices on the communication pins!

LG

**Comment by arendst** [comment]
Won't work for the dual as it uses serial to communicate with chip controlling the relays.

**Comment by Reinhartd** [comment]
The Dual and Slampher is a exception, but the normal Switch or Pow are predestined for more GPIO's!
I think, DS18b20 or DHT22 is very good and your Sketch can work with this devices.

LG

**Comment by dagbdagb** [comment]
Would this also require code to somehow re-enable RxD/TxD if the need should arise?

**Comment by Reinhartd** [comment]
a good solution is a timeout ( 1- 2 min) at power on. After 2 minutes the serial communication is automatic disabled, then we can flashing the device witout OTA.  Another idea is a switch in the Webif. 

LG

**Comment by arendst** [comment]
I would NOT consider the pow for (external) sensors:
- gnd is connected to AC which might be 240V and could harm you(r) kids
- energy monitoring  is very interrupt driven; the more power you use the more interrupts need to be serviced

You should start using seperate sensor nodes using esp-easy and hook them up with a home automation tool like  mqtt, node-red, domoticz, openhab, fhem ...

Apart from that I will consider disabling serial in a controlled fashion.

**Comment by stoehrmark** [comment]
I have been using this code with a DHT22 connected to GPIO3 TX. 
No problem just change:
#define DHT_PIN              14  
to
#define DHT_PIN              3
in the  user_config.h no other changes.
