### ISSUE TITLE
typo error under 'Prerequisite'

### ISSUE THREAD

**Issue by mitchiot** [arendst/Sonoff-MQTT-OTA-Arduino#12]
In the paragraph where you advise changes to MQTT_MAX_PACKET_SIZE & MQTT_KEEPALIVE
you have referred to **pubsubclient\src\PubSubClient.h** instead of **pubsubclient\src\MQTT.h**

**Comment by alexschomb** [comment]
Did you download the latest stable version of pubsubclient? At least in my case there is no ''MQTT.h'', but there is a ''PubSubClient.h''.

**Comment by arendst** [comment]
Thanks for responding Alex. In my case there is no MQTT.h either but only PubSubClient.h.
