### ISSUE TITLE
Can I flash Wemos D1 mini to test my setup?

### ISSUE THREAD

**Issue by yaydogan** [arendst/Sonoff-MQTT-OTA-Arduino#121]
I am waiting for Sonoff switch. Can I flash my Wemos D1 mini to test it out in my home setup?

Thanks...

**Comment by arendst** [comment]
Give it a try. What could happen? Let us know.

Btw, among others I develop on wemos1 d1 mini ...

**Comment by climberhunt** [comment]
It does work, but with a couple tweaks. 
The check in sonoff.ino for checking the value of REL_PIN at boot results in it being recognized as a SONOFF_DUAL, I force the syscfg.model to 1 at this stage. Also, I changed the GPIO pins in the cfg to use the 'D' numbers for convenience. Works well.

**Comment by arendst** [comment]
It does work as a Sonoff if you connect a relay to the correct GPIO. If not perform the undocumented command ```model 1```.

**Comment by yaydogan** [comment]
Thank you for your feedback!

**Comment by rlust** [comment]
I am trying the Wemos D1 with a relay shield. What GPIO did you use to get the relay to work?
I have a second one working using the DHT11 shield and I am getting temp readings.

**Comment by arendst** [comment]
I'm emulating Sonoff so the relay is connected to GPIO12. See user_config.h for further information
