### ISSUE TITLE
Backup Sonoff original firmware

### ISSUE THREAD

**Issue by baskinvolkan** [arendst/Sonoff-MQTT-OTA-Arduino#128]
I do not know. But, if it's possible how to backup the original firmware and how to reflash it later.
Thanks

**Comment by 0n3-70uch** [comment]
Look here:
https://forum.wemos.cc/topic/181/backup-original-firmware-with-esptool

Please test this solution (backup and flash) and tell me the result. But you will never go back to stock firmware :-).
