### ISSUE TITLE
Unable to use topic with forward slash for "topic levels"

### ISSUE THREAD

**Issue by kthamm** [arendst/Sonoff-MQTT-OTA-Arduino#13]
Hey there,

first of all I want to thank you for your great work! It works just fine for me except for one problem. I am quiete new to mqtt and arduino. I want to use topic names like home/<room>/light to be able to switch on all lights in all rooms using "home/+/light". So I changed the PROJECT variable in the sonoff.ino file to "home/myname/light". I didn't change the SUB_PREFIX variable or any other MQTT variable.
Using the MyMQTT Android-App and the topic "cmnd/home/myname/light/power" and message "toggle" doesnt do anything. It does work with a PROJECT variable like "myname" though.

Am I missing something or is this an actual bug/missing feature?

**Comment by arendst** [comment]
As designed this won't work. Feel free to amend the code to your needs.
