### ISSUE TITLE
Relay keeps switching if wifi is down

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-MQTT-OTA-Arduino#131]
Hello,
There seems to be an issue when the Sonoff loses connection to the wifi router it seems to "reset" or restart the relay. The device keeps making that clicking noise when the relay is turned on/off. The light remains on but the relay continues to make the sound.

Is this something you're able to address?

Thanks in advance

**Comment by arendst** [comment]
Get a second wifi router and configure it as the second ssid2. It tries to find a wifi connection. See #73 for more info.
