### ISSUE TITLE
Wrong status in Domoticz GUI

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-MQTT-OTA-Arduino#133]
Hello and thank you for fixing the Domoticz Status Update issues in Version 3.0.3. But there ist still another problem.

If you switch the relay with the Wall Switch, than the Domoticz Status is correct.
To reproduce the issue do the following steps:
- sonoff on with Wall Switch
- sonoff off via Domoticz Web GUI
- sonoff on with Wall switch
Now the Domoticz Web GUI show Off but the sonoff is on.

Greetings Fabi

Based on:
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/pull/130

**Comment by arendst** [comment]
What is the value of ButtonTopic? Should be 0

**Comment by 0n3-70uch** [comment]
Hi, tested and works well. Thank you.
