### ISSUE TITLE
Sonoff tries connecting to indebuurt

### ISSUE THREAD

**Issue by legolas** [arendst/Sonoff-MQTT-OTA-Arduino#135]
Despite that I did change the SSID1 and 2 inside the user_config.h I still get this output:

0:00:00 APP: Project sonoff (Topic sonoff, Fallback DVES_073FFB, GroupTopic sonoffs) Version 3.0.3
00:00:00 Wifi: Connecting to AP2 indebuurt3 (VnsqrtnrsddbrN) in mode 11N as sonoff-8187...
00:00:07 Wifi: Connect failed as AP cannot be reached
00:00:07 Wifi: Connecting to AP1 indebuurt2 (VnsqrtnrsddbrN) in mode 11N as sonoff-8187...
00:00:14 Wifi: Connect failed as AP cannot be reached
00:00:14 WPSconfig: Active for 1 minute

Obviously the connection fails.
What am I doing wrong here?

**Comment by arendst** [comment]
Use commands ssid1 and password1 to change to your wifi network. user_config.h is only used once during initial install.

Alternatively change define CFG_HOLDER.

**Comment by legolas** [comment]
Thanks for the reply.
The above log is from the first boot after install. I would've expected it to take my changes.

**Comment by legolas** [comment]
Good morning Theo,

Is it sufficient to change the "Date" (at least it looks like a date to me) value of CFG_HOLDER to a newer date to force reloading the defaults as defined in user_config.h?

**Comment by arendst** [comment]
Marcel, yep.

**Comment by legolas** [comment]
Thanks, will try that tonight when I'm home.

**Comment by legolas** [comment]
Tonight I finally had the time to test this and it works! Thank for the help.
Next step: control the sonoff using openhab.

**Comment by weerada-moria** [comment]
00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_92D241, GroupTopic sonoffs) Version 5.7.1i
00:00:00 WIF: Connecting to AP2 indebuurt2 in mode 11N as sonoff-4673...
00:00:07 WIF: Connect failed as AP cannot be reached
00:00:07 WIF: Connecting to AP1 indebuurt1 in mode 11N as sonoff-4673...
00:00:14 WIF: Connect failed as AP cannot be reached
00:00:14 WIF: WPSConfigactive for 1 minute

i found the same problem as your  how could you solve it ? i don't have any luck with this

**Comment by legolas** [comment]
@weerada-moria I would suggest switching to https://github.com/arendst/Sonoff-Tasmota
