### ISSUE TITLE
RF transmitter via Sonoff

### ISSUE THREAD

**Issue by D3-Bug** [arendst/Sonoff-MQTT-OTA-Arduino#138]
Hi there, 
To start off I want to compliment Arendst on his work in this project!

At this moment I'm using a Raspberry Pi (on the 3rd floor) to send 433MHZ signals to some switches. Some of the switches are on the ground floor and not always get the signal. 

Is it possible to connect a RF transmitter to a Sonoff on the ground floor to extent the signal coverage?

**Comment by arendst** [comment]
I guess you could connect a RF transmitter to one of sonoffs GPIOs but I would select a Wemos D1 Mini for this task. 

For the moment I won't support RF in my sonoff code as I wanted to move away form RF when I started this project anyway.

Why not send wifi commands to your sonoffs as that's what this software is all about.
