### ISSUE TITLE
Default UDP port and commands to turn the Sonoff Switch ON and OFF

### ISSUE THREAD

**Issue by WouterPieper** [arendst/Sonoff-MQTT-OTA-Arduino#140]
I've long been searching and trying, but it still does not work, maybe someone can help me
I have a Sonoff Switch which I want to put on and off with UDP command.

I read a lot about the firmware update, but if that's not necessary, I would not do that. because I have not enough knowledge in this area

I use a loxone miniserver to send UDP commands.
I need to know which UDP port is used.

I'm also need the ASCII udp commands that i can use to turn the sonoff switch ON and OFF.

I can test the commands with a udp sender on my windows computer. 
For example i have another webrelais that already work. 
I attached a picture of this example.
To turn OFF this webrelais i use port 1200 and ASCII command: u=2password\n
To turn ON this webrelais i use port 1200 and ASCII command: a=2password\n

is there anyone who can tell me which port and commands for ON and OFF i can use for the sonoff switch?
Or is it not possible to turn the switch ON and OFF on this way without updated the firmware of the sonoff switch?

![2 webrelais sample](https://cloud.githubusercontent.com/assets/24544292/21140562/06f7e084-c139-11e6-8cb2-7279bae68dc0.JPG)

**Comment by Lennyz1988** [comment]
You should find help at the forum of Itead. This has nothing to do with the firmware Sonoff-MQTT-OTA-Arduino by Arendst.

**Comment by arendst** [comment]
As said by Lennyz this software does not support UDP other than the initial Amazon Alexa communication. 

For the original sonoff software you'll have to contact iTead.
