### ISSUE TITLE
Deactivate LEDs blinkings in Normal-Mode

### ISSUE THREAD

**Issue by thommycgn** [arendst/Sonoff-MQTT-OTA-Arduino#143]
The LEDs of the Sonoffs are really light and blinking from time to time. Not really nice in the sleeping room by night. It would be great if you could realize an option in Configuration Panel to prevent this.
Is it possible?

**Comment by thomasf** [comment]
Maybe related to #136

**Comment by 0n3-70uch** [comment]
Hello, please Test this MQTT command:
LedState off

Look here for more informations:
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/wiki/Commands

I don't know if this command will hot of the blinking but it is you can Test it.

Greetings Fabi

**Comment by arendst** [comment]
Guys, been away for some days and this is on top of my list. ledstate off won't do it right now but I'll change it's options to allow disabling all blinks.

**Comment by arendst** [comment]
Several options added to command LedState allowing more control over it's use in version 3.0.5 just released.

See wiki or _releasenotes.ino
