### ISSUE TITLE
Temperature & Humidity troubleshoot info needed

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-MQTT-OTA-Arduino#145]
I am trying to get a DHT22 connected. I am not seeing any messages or commands on how to trouble shoot this. I have selected the pin it is connected to and tried both options of configuration for the DHT. Any ideas would be helpful.

**Comment by arendst** [comment]
Enable logging either with seriallog 3, weblog 3 or syslog 3 then you should receive some more info.

**Comment by rlust** [comment]
That helped! 
One further question, I see code to convert C to F temp but not able to see how that is triggered?

Great job on this project! Well done!!

**Comment by rlust** [comment]
That helped!
One further question, I see code to convert C to F temp but not able to see how that is triggered?

Great job on this project! Well done!!

**Comment by arendst** [comment]
Working on overall C/F option...

**Comment by arendst** [comment]
Implemented optional conversion to Fahrenheit in version 3.0.8 just released.
