### ISSUE TITLE
Itead Sonoff Second Relay

### ISSUE THREAD

**Issue by pacitzu** [arendst/Sonoff-MQTT-OTA-Arduino#153]
it would be useful to add the Domoticz Idx configuration of the second relay.
In Domoticz panel it is only for the first Relay

**Comment by arendst** [comment]
Although there is no configuration item on the webpage you can still configure it using command ```DomoticzIdx2``` as long as the hardware supports and recognized two relays.

**Comment by arendst** [comment]
Version 3.1.3 released today will show indices for all relays present.

**Comment by pacitzu** [comment]
Thank
