### ISSUE TITLE
Feature Request: Add the ability to define a default power state on startup.

### ISSUE THREAD

**Issue by crankyoldgit** [arendst/Sonoff-MQTT-OTA-Arduino#154]
Currently the default appears to be on initial sonoff power on to have the power off, or to load from the previous state if that state saving is turned on. I'd like the ability to define a behaviour of "Always turn the power relay to 'on' when the sonoff gets power initially".
The scenario where this is useful is when the sonoff is down the line from a power switch. e.g. a light switch. A typical person would expect the light to come on. This would allow consistency for people who don't have the ability to use smart home features, and also cover failure cases where network connectivity or automation control is unavailable.
With the sonoff downstream of the physical switch and configured as above it is possible to go to a no-power state to save electricity by having the sonoff completely powered off, and allow a physically present person to have ultimate control like they used to. (i.e. Spouse Approval Factor)

Note: I tried changing the default for APP_POWER to 1, that didn't work.
I also tried setting the power to 1, saving the state, then turning off state save, but it appears it will only load the previous saved state on reboot if state saving is turned on.

Thanks in advance.

**Comment by arendst** [comment]
Implemented in version 3.1.1 just released.

Use command PowerOnState to select either 0 = Off after power on, 1 = On after power on or 2 = Use last saved state.
