### ISSUE TITLE
relay state after a reboot

### ISSUE THREAD

**Issue by jesusvallejo** [arendst/Sonoff-MQTT-OTA-Arduino#156]
I've seen a command that enables the option of puting the relay in the previous saved mode , could it be possible an implementation that does not put it on the saved mode, but toggles it.

thank you 

(pardon me if it is not well tagged , i do not know how to tag it as a question)

**Comment by arendst** [comment]
Implemented in version 3.1.2 just released.

**Comment by jesusvallejo** [comment]
Thank you , where may i find the commands implemented on the new release

**Comment by arendst** [comment]
See the wiki on the top of this page. On the right you'll find a link to many commands available.
