### ISSUE TITLE
"File upload buffer miscompare" when OTA a modified firmware

### ISSUE THREAD

**Issue by Nayar** [arendst/Sonoff-MQTT-OTA-Arduino#157]
Hi,

In what conditions do I get "File upload buffer miscompare" when uploading a new firmware? I added a functions and it didn't want to upload. When flashing to device through wire, it seems to work.

**Comment by arendst** [comment]
You compiled with wrong flash option; either 512 flash or no or  to much spiffs.

**Comment by eifinger** [comment]
Hi there, I just wanted to upload version 3.1.3 via File Upload and got the same error. I made sure I compiled the file with the correct flash options.
Will now try the other OTA method.

**Comment by eifinger** [comment]
Thank you very much for clarifying that.
Works like a treat now.

Thank you for the support and the awesome software!

**Comment by julred** [comment]
Hi,
I have the same issue.
I flashed the latest spftware 5.14.0 via Arduino with the following preferences:
Flash mode: DOUT
Flash size: 1M (64k SPIFFS)

This is extracted from the information page:


ESP Chip Id        11028069
Flash Chip Id     1327198
Flash Size          1024kB
Program Flash Size  1024kB
Program Size  560kB
Free Program Space  376kB
Free Memory 17kB


And trying to upload a binary file (sonoff-DE.bin) generates the following error message:
Upload Failed

Upload buffer miscompare

**Comment by littlebilly** [comment]
Hi,
I have the same issue with 5.14.0
Flashing Version 5.12.0i-2_3_0 works without any error message.
-----------------
Solution 
https://github.com/arendst/Sonoff-Tasmota/wiki/Upgrade
Larger firmware files can only be loaded when the current flash usage is first reduced to accommodate more free flash to load the new firmware. Hence you'll need to perform a two step process:
Upload firmware with #define USE_MINIMAL enabled which will have a smaller footprint
Upload the final firmware with #define USE_MINIMAL disabled with the features you want to use.

Flashing firstly sonoff-minimal.bin than flashing eg sonoff-DE.bin does it.

Billy

**Comment by microspino** [comment]
@littlebilly you saved my day.
Uploading sonoff-minimal then sonoff-classic did the trick. THX

**Comment by mskrohn** [comment]
> @littlebilly you saved my day.
Uploading sonoff-minimal then sonoff-classic did the trick. THX

This worked!  Thank you!

**Comment by tifrei** [comment]
Hi @ all,

I have the same error and cant upgrade my sonoff T1 2CH. 

Flashed with DOUT (1M 65K Spifs) 

When i try to upload the minimal version it still said Upload buffer miscompare. 

Is there any other solution or am i doing something wrong? is #define use_minimal a command i have to put in the console before uploading?

Thx in advance
