### ISSUE TITLE
Get only state of GPIO

### ISSUE THREAD

**Issue by Nayar** [arendst/Sonoff-MQTT-OTA-Arduino#158]
Hi,

I am connecting a `HC-SR501` to my sonoff. However I wish to send the state only via MQTT so that my external server can decide what to do. e.g. it makes no sense to power on lights during the day when motion detected. I want my logics to be on the server-side.

The closest I've seen in the configs is `#define USE_WALL_SWITCH `. Is there an option that when activated, only sends something like `/stat/GPIO ON` or something. An option like `STAT` for `SWITCH_MODE` would be great.

**Comment by arendst** [comment]
Define a ButtonTopic and you'll receive a cmnd/<ButtonTopic>/POWER message.

**Comment by arendst** [comment]
See #141 too

**Comment by Nayar** [comment]
Unfortunately it changes the topic of the physical button of the sonoff itself. I'll try to see what can be done
