### ISSUE TITLE
WeMo Emulator - Alexa support

### ISSUE THREAD

**Issue by wiktorschmidt** [arendst/Sonoff-MQTT-OTA-Arduino#161]
There seems to be a quite easy way for adding Alexa support to sonoff via WeMo emulation:

https://github.com/kakopappa/arduino-esp8266-alexa-wemo-switch

Maybe worth considering for future releases.

**Comment by wiktorschmidt** [comment]
sorry - looks like it's there already - missed it :)

**Comment by ThomDietrich** [comment]
Interesting ;) For who might be interested: openHAB 2 has an Alexa skill (waiting to be activated by Amazon)
