### ISSUE TITLE
Feature request: Does this firmware support Sonoff PSB-04 

### ISSUE THREAD

**Issue by rajtan** [arendst/Sonoff-MQTT-OTA-Arduino#170]
Hi, Does this firmware also support 4 channel module from sonoff, named PSB-04? Though this is 4 Channel device but different from Sonoff 4 Ch in hardware.

**Comment by arendst** [comment]
Yes, it's like sonoff dual. Once installed firmware type command ```Model 3``` and you should be good to go.

I haven't tested it though...
