### ISSUE TITLE
Support of "1 Channel Inching /Self-Locking WiFi Wireless Switch 5V 12V"

### ISSUE THREAD

**Issue by lionhe1966** [arendst/Sonoff-MQTT-OTA-Arduino#178]
Do you plan to add support for this device ?
https://www.itead.cc/inching-self-locking-wifi-wireless-switch.html
I've read on itead forum that someone was able reflash it, even though there was a problem with the header pins.
http://support.iteadstudio.com/support/discussions/topics/11000009218

 I've just ordered one to control a gas boiler.
Thank you,

**Comment by arendst** [comment]
See #159. Seems to work.

**Comment by lionhe1966** [comment]
Thank you for your answer. I updated the wiki to mention also this device. I'll test as soon as I will receive it.

**Comment by lionhe1966** [comment]
I recently bought from Banggood this switch and I found that this firmware works but the RELAY_PIN is connected to GPIO13 instead of GPIO12.  Maybe there are different versions of this switch around.

**Comment by putos11** [comment]
@lionhe1966 ,,
I can confirm,,  I had to connect to esp8266 both RX and TX pins too..
how did you get into Flash/programming mode??

**Comment by lionhe1966** [comment]
@putos11
I basically followed the  wiki instructions: if i remember well,  you have to connect the ftdi programmer to the board,  press a button and then  connect the ftdi programmer to the pc.
