### ISSUE TITLE
Feature request: Remote configure Sonoff type

### ISSUE THREAD

**Issue by smadds** [arendst/Sonoff-MQTT-OTA-Arduino#182]
Would it be possible to configure the Sonoff board type and sensor after installing the software? It would be more convenient to have one binary image with the configurations stored in the unit's flash if there is space to compile the different options.

(I'm asking after flashing a Dual and a TH16 with updated software and realising the TH is not now recognising the sensor)

**Comment by arendst** [comment]
That's what OTA is for.

**Comment by smadds** [comment]
But isn't local flash used for keeping configuration so that the codebase
does not need editing each time there is an update? What's the point if we
still need to edit it to compile different binaries for the sonoff
variations?

Or am I missing something?

**Comment by ecsfang** [comment]
I interpreted @smadds question to why we don't have a single binary, one to rule them all, and then do all configuration on each device?
That way I could OTA upgrade all devices (being Basic, TH, Pows or whatever) with one single binary.
And in the best of worlds, the binary itself should detect the hardware (number of relays, temp sensors etc), but that might be to set the hurdle to high ... ;)
Just my 2 cents, cheers!

**Comment by arendst** [comment]
Asking a question is answering it.

Having all we want in one image is what we all want but:
- some things exclude another
- 1M flash for program storage means making choices about functionality and user experience
- 64k parameter storage lowers usable flash size
- OTA cuts useable flash size in half

Current image with TLS is already challenging and approaching max program size.

So as always there are catches and choices to make but having OTA anything is possible...

**Comment by smadds** [comment]
I can understand that, especially with the TLS option. 

Would still be great to enable sensors without re-flashing though...

**Comment by arendst** [comment]
Working on some kind of 'one size fits all'...

**Comment by arendst** [comment]
Have a look in the experimental folder where I released a beta of the way I would like to go forward. Pls read the readme too.

**Comment by smadds** [comment]
This is looking really good!
At the moment, I don't seem to be able to communicate with my MQTT server. I go into the web server settings (in between the long timeouts for MQTT) and set the new server, but it does not connect to my MQTT server. Has anyone else had this issue with the experimental version?

**Comment by arendst** [comment]
NextGen Version 3.9.3 contains a lot of Domoticz updates like defining sensor indexes to supported sensors. See Domoticz Configuration webpage for more information.
