### ISSUE TITLE
Sonoff (standard) GPIO14?

### ISSUE THREAD

**Issue by Djsajmy** [arendst/Sonoff-MQTT-OTA-Arduino#189]
Didn't know where to ask!

Do the standard Sonoff's use/have the GPIO14 on the PCB and if can it be used for the wall switch toggle like on the TH10/16 or do I need the TH version for that?

Thanks.

**Comment by jaysuk** [comment]
They have GPIO14. It's the 5th pin next to the 4 for uploading the code. I use one with lights in my garage. Works perfectly with my wall switch
