### ISSUE TITLE
Wiki Commands cleanup

### ISSUE THREAD

**Issue by stoehrmark** [arendst/Sonoff-MQTT-OTA-Arduino#193]
Don't know if you are interested but i have shortened the commands form from the Wiki page. Combining same commands and removing duplicates.  Here is a link

https://docs.google.com/spreadsheets/d/1bsCs3x2sGZ8ZTg3fTuZM3MUP5Ui3EGlgNLXrITyorNc/edit?usp=sharing

**Comment by arendst** [comment]
Looks good. I'll look into it.

**Comment by arendst** [comment]
Made a copy of it. Updated layout a bit and made it available as a link in the wiki command section. Thnx.
