### ISSUE TITLE
Feature request: Allow all time settings to be set via the console.

### ISSUE THREAD

**Issue by crankyoldgit** [arendst/Sonoff-MQTT-OTA-Arduino#194]
Currently you can't change NTP_SERVER1, NTP_SERVER2, NTP_SERVER3, TIME_DST, TIME_STD, or APP_TIMEZONE via the console.

You have to override it in user_config*.h instead. It would be terribly nice if these could be set via the console.

**Comment by arendst** [comment]
I think you only update this once for your location so it doesn't justify the amount of code I have to write to satisfy all wrong user input (as that takes most of the work).

**Comment by crankyoldgit** [comment]
Fair call. It just meant I could move away from having a custom user_config_override.h
Oh FYI, I was wrong, timezone is already an existing command.
