### ISSUE TITLE
Feature request: OTA supported from Arduino IDE -> Sonoff

### ISSUE THREAD

**Issue by allthepies** [arendst/Sonoff-MQTT-OTA-Arduino#203]
Hi,  I see that the code supports OTA but I'm not sure if I can perform the update directly from the Arduino IDE to the Sonff ?   A network port did once appear in the IDE "ports" list but when I attempted to perform a compile/upload to that network port then I received a not-listening type error.  

And, when I enabled Alexa support then the network port disappeared from the port list.  Is that a deliberate action ?  Or does the sketch size become too big to support OTA with Alexa support enabled ?

**Comment by arendst** [comment]
OTA is supported using a webserver and initiated via MQTT as documented in the wiki. I never supported OTA via IDE other than uploading the file to a webserver as I failed to receive any port in the IDE.
