### ISSUE TITLE
Idea:Discussion Forum

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-MQTT-OTA-Arduino#205]
Apologies for raising this as an issue. It's more an idea.

Does anyone know a forum where we can discuss all @arendst and Sonoff related projects and ideas. I am particularly interested in how others are using various Sonoff devices around their homes etc.

**Comment by rlust** [comment]
Good idea! How about a google group?

**Comment by arendst** [comment]
You may start it and I might join in.

**Comment by jaysuk** [comment]
Would you be happy with a google groups forum being set up?

**Comment by tam481** [comment]
Shall I set it up? Happy to do so.

**Comment by arendst** [comment]
tam481, be my guest

**Comment by jaysuk** [comment]
Go for it. I can help moderate

**Comment by tam481** [comment]
https://groups.google.com/d/forum/sonoffusers

**Comment by tam481** [comment]
@jaysuk and @arendst please join in and I'll make you moderators :-)

**Comment by arendst** [comment]
Links added to both Readme and wiki.
