### ISSUE TITLE
ButtonTopic with toggle switches

### ISSUE THREAD

**Issue by andrewradke** [arendst/Sonoff-MQTT-OTA-Arduino#207]
In send_button_power if the state is 2 (toggle relay) MQTT_STATUS_ON is always sent instead.
A quick and dirty fix that has worked for me is:

```
    if (state == 2) {
      snprintf_P(svalue, sizeof(svalue), PSTR("%s"), "2");
//      state = ~(power >> (device -1)) & 0x01; 
    } else {
      snprintf_P(svalue, sizeof(svalue), PSTR("%s"), (state) ? MQTT_STATUS_ON : MQTT_STATUS_OFF);
    }
```

Is there any problems with this or is there a better solution?

**Comment by arendst** [comment]
When using ButtonTopic and the name is different from Topic it indeed would only send an ON command.

I've changed it's behaviour when ButtonTopic is different it now sends a TOGGLE command as was suggested here.

Problem was that ButtonTopic toggled related to current relay power state but if the ButtonTopic is different from the Topic it's commands are not meant for this relay. Toggling is then the best option.

**Comment by andrewradke** [comment]
Thank you. That was an extremely quick bug fix :-) 👍
