### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by Andrijano** [arendst/Sonoff-MQTT-OTA-Arduino#21]
config:30: error: redefinition of 'void CFG_Default()'

**Comment by arendst** [comment]
?

**Comment by arendst** [comment]
You seem to be using a version older than 1.0.16.
I recommend downloading the latest being 1.0.30 and retry.

**Comment by petermoffat** [comment]
Version 1.0.30 of what?

**Comment by Andrijano** [comment]
The issue is not solved, config:30: error: redefinition of 'void
CFG_Default()'.I m using 1.6.12 with recent 2.0.6 version.

2016-09-02 11:22 GMT+02:00 Theo Arends <notifications@github.com>:

**Comment by arendst** [comment]
Please copy the complete error message (all lines) provided by the IDE. Also copy the first 40 lines of your file ```config```.

To my knowledge there is no file called ```config``` in my repository so I have no idea where this message is coming from.

**Comment by Andrijano** [comment]
extern "C" {
#include "spi_flash.h"
}

extern "C" uint32_t _SPIFFS_end;
#define CFG_LOCATION (((uint32_t)&_SPIFFS_end - 0x40200000) /
SPI_FLASH_SEC_SIZE) - 2  // End of SPIFFS area

SYSCFG myCfg;

void CFG_Save()
{
  char log[80];

  if (memcmp(&myCfg, &sysCfg, sizeof(SYSCFG))) {
    noInterrupts();
    if (sysCfg.saveFlag == 0) {  // Handle default and rollover
      spi_flash_erase_sector(CFG_LOCATION + (sysCfg.saveFlag & 1));
      spi_flash_write((CFG_LOCATION + (sysCfg.saveFlag & 1)) *
SPI_FLASH_SEC_SIZE, (uint32 *)&sysCfg, sizeof(SYSCFG));
    }
    sysCfg.saveFlag++;
    spi_flash_erase_sector(CFG_LOCATION + (sysCfg.saveFlag & 1));
    spi_flash_write((CFG_LOCATION + (sysCfg.saveFlag & 1)) *
SPI_FLASH_SEC_SIZE, (uint32 *)&sysCfg, sizeof(SYSCFG));
    interrupts();
    sprintf_P(log, PSTR("Config: Saved configuration to flash at %X and
count %d"), CFG_LOCATION + (sysCfg.saveFlag & 1), sysCfg.saveFlag);
    addLog(LOG_LEVEL_DEBUG, log);
    myCfg = sysCfg;
  }
}

void CFG_Default()
{
  addLog(LOG_LEVEL_INFO, "Config: Use default configuration");
  memset(&sysCfg, 0x00, sizeof(SYSCFG));
  memset(&myCfg, 0x00, sizeof(SYSCFG));
  sysCfg.cfg_holder = CFG_HOLDER;
  sysCfg.saveFlag = 0;
  sysCfg.version = VERSION;
  sysCfg.seriallog_level = SERIAL_LOG_LEVEL;
  sysCfg.syslog_level = SYS_LOG_LEVEL;
  strcpy(sysCfg.syslog_host, SYS_LOG_HOST);
  strcpy(sysCfg.sta_ssid, STA_SSID);
  strcpy(sysCfg.sta_pwd, STA_PASS);
  strcpy(sysCfg.otaUrl, OTA_URL);
  strcpy(sysCfg.mqtt_host, MQTT_HOST);
  strcpy(sysCfg.mqtt_grptopic, MQTT_GRPTOPIC);
  strcpy(sysCfg.mqtt_topic, MQTT_TOPIC);
  strcpy(sysCfg.mqtt_topic2, "0");
  strcpy(sysCfg.mqtt_subtopic, MQTT_SUBTOPIC);
  sysCfg.timezone = APP_TIMEZONE;
  sysCfg.power = APP_POWER;
  sysCfg.ledstate = APP_LEDSTATE;
  CFG_Save();
}

void CFG_Load()
{
  char log[80];

  noInterrupts();
  spi_flash_read((CFG_LOCATION) * SPI_FLASH_SEC_SIZE, (uint32 *)&sysCfg,
sizeof(SYSCFG));
  spi_flash_read((CFG_LOCATION + 1) * SPI_FLASH_SEC_SIZE, (uint32 *)&myCfg,
sizeof(SYSCFG));
  interrupts();
  if (sysCfg.saveFlag < myCfg.saveFlag) sysCfg = myCfg;
  sprintf_P(log, PSTR("Config: Loaded configuration from flash at %X and
count %d"), CFG_LOCATION + (sysCfg.saveFlag & 1), sysCfg.saveFlag);
  addLog(LOG_LEVEL_DEBUG, log);
  if (sysCfg.cfg_holder != CFG_HOLDER) CFG_Default();
  myCfg = sysCfg;
}

void CFG_Erase()
{
  char log[80];
  SpiFlashOpResult result;

  uint32_t _sectorStart = (ESP.getSketchSize() / SPI_FLASH_SEC_SIZE) + 1;
  uint32_t _sectorEnd = ESP.getFlashChipRealSize() / SPI_FLASH_SEC_SIZE;
  byte seriallog_level = sysCfg.seriallog_level;

  sprintf_P(log, PSTR("Config: Erasing %d flash sectors"), _sectorEnd -
_sectorStart);
  addLog(LOG_LEVEL_DEBUG, log);

  for (uint32_t _sector = _sectorStart; _sector < _sectorEnd; _sector++) {
    noInterrupts();
    result = spi_flash_erase_sector(_sector);
    interrupts();
    if (LOG_LEVEL_DEBUG_MORE <= seriallog_level) {
      Serial.print(F("Flash: Erased sector "));
      Serial.print(_sector);
      if (result == SPI_FLASH_RESULT_OK)
        Serial.println(F(" OK"));
      else
        Serial.println(F(" Error"));
      delay(10);
    }
  }
}



Arduino: 1.6.12 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, 40MHz,
DIO, 115200, 1M (64K SPIFFS), ck, Disabled, None"

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\config.ino:
In function 'void CFG_Default()':

config:30: error: redefinition of 'void CFG_Default()'

 void CFG_Default()

      ^

sonoff:244: error: 'void CFG_Default()' previously defined here

 void CFG_Default()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\support.ino:
In function 'void CFG_Save()':

support:56: error: redefinition of 'void CFG_Save()'

 void CFG_Save()

      ^

config:10: error: 'void CFG_Save()' previously defined here

 void CFG_Save()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\support.ino:
In function 'void CFG_Load()':

support:92: error: redefinition of 'void CFG_Load()'

 void CFG_Load()

      ^

config:55: error: 'void CFG_Load()' previously defined here

 void CFG_Load()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\support.ino:
In function 'void CFG_Erase()':

support:130: error: redefinition of 'void CFG_Erase()'

 void CFG_Erase()

      ^

config:70: error: 'void CFG_Erase()' previously defined here

 void CFG_Erase()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\support.ino:
At global scope:

support:430: error: redefinition of 'const uint8_t monthDays []'

 static const uint8_t monthDays[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30,
31, 30, 31 }; // API starts months from 1, this array starts from 0

                                ^

rtc:11: error: 'const uint8_t monthDays [12]' previously defined here

 static const uint8_t monthDays[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30,
31, 30, 31 }; // API starts months from 1, this array starts from 0

                      ^

support:431: error: redefinition of 'const char monthNames [37]'

 static const char monthNames[37] = {
"JanFebMrtAprMayJunJulAugSepOctNovDec" };

                                ^

rtc:13: error: 'const char monthNames [37]' previously defined here

 static const char monthNames[37] = {
"JanFebMrtAprMayJunJulAugSepOctNovDec" };

                   ^

support:434: error: redefinition of 'uint8_t ntpsync'

 uint8_t ntpsync = 0;

         ^

rtc:16: error: 'uint8_t ntpsync' previously defined here

 uint8_t ntpsync = 0;

         ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\support.ino:
In function 'void rtc_second()':

support:572: error: redefinition of 'void rtc_second()'

 void rtc_second()

      ^

rtc:77: error: 'void rtc_second()' previously defined here

 void rtc_second()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\wifi.ino:
In function 'void WIFI_check_ip()':

wifi:17: error: redefinition of 'void WIFI_check_ip()'

 void WIFI_check_ip()

      ^

support:300: error: 'void WIFI_check_ip()' previously defined here

 void WIFI_check_ip()

      ^

C:\Users\Andrijano\Desktop\kontrol\arduino-1.6.12\portable\sketchbook\sonoff\wifi.ino:
In function 'void WIFI_Connect(char*)':

wifi:77: error: redefinition of 'void WIFI_Connect(char*)'

 void WIFI_Connect(char *Hostname)

      ^

support:389: error: 'void WIFI_Connect(char*)' previously defined here

 void WIFI_Connect(char *Hostname)

      ^

exit status 1
redefinition of 'void CFG_Default()'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.





Many thanks in advance




Andrijano





2016-10-31 16:37 GMT+01:00 Theo Arends <notifications@github.com>:

**Comment by arendst** [comment]
Andrijano, you have a basic version update problem: If you use a new version you'll have to delete ALL files from your sonoff directory and copy the new ones from Github.

In your case there still are files called config.ino and wifi.ino which have been deleted since version 1.0.16

**Comment by Andrijano** [comment]
Many thanks, now it seems ok.

Best Regards


Andrijano

2016-11-01 10:28 GMT+01:00 Theo Arends <notifications@github.com>:
