### ISSUE TITLE
Feature Request: HomeKit support

### ISSUE THREAD

**Issue by felixekman** [arendst/Sonoff-MQTT-OTA-Arduino#211]
How about adding HomeKit support? There is an amazing project going on here:
https://github.com/HomeACcessoryKid/ESP8266-HomeKit-Demo

I'm imagining MQTT/Alexa/HomeKit co-exisiting with the Sonoff and being amazing!

**Comment by arendst** [comment]
Looked at it:
```
Memory: The HomeKit code is approximately 400K and about 18K of RAM is left for other purposes.
```
I have only 450K to play with to keep OTA available on 1M flashes so I am afraid it's a bridge to far for my software, homekit and sonoff.

I suggest to use a home automation tool that both supports sonoff via MQTT (my software) and homekit. That's more flexible too.

**Comment by felixekman** [comment]
How about maybe adding a different branch of your git for either W25Q32FV implementations or one without OTA-support?
