### ISSUE TITLE
Domoticz: Configuration item missing in latest

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-MQTT-OTA-Arduino#215]
I just updated a module to the latest version and now cannot see the domoticz configuration menu.
Did I miss a config option?

**Comment by arendst** [comment]
Don't you miss MQTT functionality too?

If so then you missed the new define USE_MQTT in user_config.h by popular demand...

**Comment by krajcl** [comment]
I wonder if it is possible that the dual button press (multipress 2) toggle different switch in domoticz, similar to sonoff dual, but on sonoff touch (single press - toggle relay and switch idx1 in domoticz, two short presses toggles switch idx2 in domoticz) ?

**Comment by rlust** [comment]
I installed the latest release and all is well, thanks!
