### ISSUE TITLE
WiFi password visible in console in plain text.

### ISSUE THREAD

**Issue by RobKuipers** [arendst/Sonoff-MQTT-OTA-Arduino#216]
Example:
00:00:00 Wifi: Connecting to AP2 MyAP (**thisisthepasswordinplaintext**) in mode 11N as buitenlamp-4854...

Could the password be hidden please? I don't think it has much added value for anyone (of good faith).

Regards,
Rob

**Comment by arendst** [comment]
Will do

**Comment by RobKuipers** [comment]
Wow! You're fast!
Thanks Theo.

**Comment by andrewradke** [comment]
I was thinking the same, both about the password in plain text in a few places and about the speed of Theo's responses. :-)
