### ISSUE TITLE
Domoticz Temp & Humidity Integration

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-MQTT-OTA-Arduino#219]
Would it be possible to have an IDX variable assigned to the JSON string for telemetry data to allow this to be used as an input into Domoticz?

Thanks for all of your fantastic work on this software! Well done!!

**Comment by 0n3-70uch** [comment]
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/issues/86

**Comment by arendst** [comment]
NextGen Version 3.9.3 contains a lot of Domoticz updates like defining sensor indexes to supported sensors. See Domoticz Configuration webpage for more information.

**Comment by 0n3-70uch** [comment]
Oh nice thank you very much.
