### ISSUE TITLE
Any plan to support RF receiver equipped SonOff?

### ISSUE THREAD

**Issue by hjgode** [arendst/Sonoff-MQTT-OTA-Arduino#22]
At itead there is a sonoff with built in RF receiver. The original firmware then supports pairing with a RF remote (433MHz?).

Are there any plans to support the RF receiver with Sonoff-MQTT? For example using an arduino lib as the one here: https://github.com/yoh-there/RemoteSwitch

**Comment by arendst** [comment]
No I do not plan to do anything with RF as it was my idea to get rid of it by replacing it with Wifi,

Sorry, Theo.

**Comment by hjgode** [comment]
OK, I understand. So I will try espurna for that requirement.

Thanks a lot

Josef
