### ISSUE TITLE
SLAMPHER flash problems

### ISSUE THREAD

**Issue by tomskidoodle** [arendst/Sonoff-MQTT-OTA-Arduino#223]
Are there any known problems flashing Slampher devices?  These aren't listed in user_config.h as a valid module and I get a 'version invalid' error when I try to upload.

I can flash basic SONOFF modules without any problems.

Cheers

Tom

**Comment by Reinhartd** [comment]
i have flashed the Slampher with normal settings Sonoff 1M, 64K SPIFFS ( define MODULE SONOFF ) .
you can see here: [https://wiki.fhem.de/wiki/Sonoff#Sonoff_Slampher_Flashen](url)

LG
