### ISSUE TITLE
Question : Video instruction

### ISSUE THREAD

**Issue by Dietmar-Franken** [arendst/Sonoff-MQTT-OTA-Arduino#226]
Has anyone a link to a video instruction on how to flash a Sonoff or can make one?

**Comment by kfonda** [comment]
This is the first one I saw, it's how I found this firmware. :-)
http://www.superhouse.tv/17-home-automation-control-with-sonoff-arduino-openhab-and-mqtt/

**Comment by Dietmar-Franken** [comment]
@kfonda Thank you i´ll take a look
