### ISSUE TITLE
PowerOnState 2 Broken?

### ISSUE THREAD

**Issue by Hogesyx** [arendst/Sonoff-MQTT-OTA-Arduino#230]
It currently only work properly on graceful reboot. Not sure if I am using it wrong, might dig deeper later.

Seems to be a useful option if we are able to use the original power switch as a toggle switch.

**Comment by arendst** [comment]
Fixed in version 3.2.2 just released

**Comment by Hogesyx** [comment]
Wow, you are really fast.
