### ISSUE TITLE
Is there a way to change the LED settings after a device is flashed?

### ISSUE THREAD

**Issue by davidelang** [arendst/Sonoff-MQTT-OTA-Arduino#239]
I want to have some devices have the LED on if the switch is on and others I want only light when there is communication, and others no light at all.

Rather than compiling different firmware for each of them, I'd rather set it after flashing.

**Comment by arendst** [comment]
David, the wiki might be good starting point. May I suggest the commands section...

**Comment by davidelang** [comment]
Thanks, I missed that.
