### ISSUE TITLE
is there a way to do OTA from Sonoff-MQTT-OTA to Sonoff-MQTT-OTA-Arduino?

### ISSUE THREAD

**Issue by davidelang** [arendst/Sonoff-MQTT-OTA-Arduino#241]
I have some switches that were flashed with the Sonoff-MQEE-OTA firmware that I now want to move to the -Arduino version. Is there a way for me to take the sonoff.ino.bin file and replace the user1.bin or user2.bin files that were used for the older firmware?

file reports differently for the different .bin files so it's not clear if I can get away with just overwriting the old firmware and doing the 4-click OTA update on the switches.

**Comment by arendst** [comment]
#28
