### ISSUE TITLE
Alexa discover devices needs MQTT

### ISSUE THREAD

**Issue by don-willingham** [arendst/Sonoff-MQTT-OTA-Arduino#245]
When I select "Discover devices" in the Alexa app, it doesn't not find my sonoff. I then run mosquitto (mqtt broker), and try again, Alexa then discovers my sonoff.

**Comment by arendst** [comment]
Should be fixed in version 3.2.3 just released

**Comment by citrusfizz** [comment]
I tried on 3.2.3   couldn't get it to work with MQTT disabled,  but i didn't tinker much.   Once in enabled MQTT again, it discovered it.  just my 2 cents, again i only tried for like 5 minutes
