### ISSUE TITLE
Idea: use environments in PlatformIO to differentiate hardware

### ISSUE THREAD

**Issue by wiktorschmidt** [arendst/Sonoff-MQTT-OTA-Arduino#248]
Hey @arendst,

I thought you might find this interesting.

A pretty cool pattern:
https://bitbucket.org/xoseperez/espurna/src/190a540cd2963215d54f87b211643a76b4b68e62/code/platformio.ini?at=master&fileviewer=file-view-default#platformio.ini-37

Can be used to replace the a little obscure define method:
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/blob/master/sonoff/user_config.h#L12

Just an idea.

**Comment by arendst** [comment]
Have a look in the experimental folder. Almost no setup needed as all modules are compiled in as one image...
Once uuploaded all config is done online.

**Comment by wiktorschmidt** [comment]
Interesting. I'll take a look. Thanks!

**Comment by wiktorschmidt** [comment]
Works great. It's missing a platformio.ini the folder though :)
