### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by vzorglub** [arendst/Sonoff-MQTT-OTA-Arduino#253]
Hello,
I have changed my settings in user_config.h and the sketch is not compiling
I have errors I have not seen before:

sonoff:76: error: variable or field 'IPtoCharArray' declared void
sonoff:76: error: 'IPAddress' was not declared in this scope
sonoff:76: error: expected primary-expression before 'char'
sonoff:76: error: expected primary-expression before 'size'
sonoff:92: error: 'TIME_T' has not been declared
sonoff:93: error: 'TIME_T' was not declared in this scope
sonoff:93: error: 'tm' was not declared in this scope
sonoff:94: error: 'TimeChangeRule' was not declared in this scope
sonoff:94: error: expected primary-expression before 'int'
sonoff:94: error: expression list treated as compound expression in initializer [-fpermissive]
sonoff:99: error: variable or field 'rtc_init' declared void
sonoff:99: error: 'rtcCallback' was not declared in this scope
sonoff:103: error: 'IPAddress' has not been declared
sonoff.ino: In function 'void setup()':
sonoff:2584: error: 'rtc_init' was not declared in this scope
support.ino: In function 'boolean mdns_discoverMQTTServer()':
support:594: error: 'IPtoCharArray' was not declared in this scope
support.ino: In function 'uint32_t makeTime(TIME_T&)':
support:895: error: 'uint32_t makeTime(TIME_T&)' redeclared as different kind of symbol
sonoff:93: error: previous declaration of 'uint32_t makeTime'
support.ino: In function 'uint32_t toTime_t(TimeChangeRule, int)':
support:926: error: 'uint32_t toTime_t(TimeChangeRule, int)' redeclared as different kind of symbol
sonoff:94: error: previous declaration of 'uint32_t toTime_t'
support:948: error: 'makeTime' cannot be used as a function
support.ino: In function 'void rtc_second()':
support:1000: error: 'toTime_t' cannot be used as a function
support:1001: error: 'toTime_t' cannot be used as a function variable or field 'IPtoCharArray' declared void

My board manager settings are correct as recommended on the wiki
I am using v1.6.5 of the IDE on Ubuntu Linux
All my other sketches compile fine with the Ticker and ESP and PubSub libraries.

Can you help, please? I have two sonoffs coming soon and I can't wait to play with them.

Thanks
Vincent

**Comment by arendst** [comment]
IDE 1.6.5 is not supported. See wiki about the current supported versions (IDE 1.6.10 up and ESP 2.3.0).
