### ISSUE TITLE
Wiki "Compile and Upload" Suggestions

### ISSUE THREAD

**Issue by tysenmoore-xse** [arendst/Sonoff-MQTT-OTA-Arduino#263]
First off, thanks so much for the great work on the project.  I am just starting off with my first SONOFF POW / OpenHab2 project and what you've done here makes these products so much more customizable.  

In going through the Wiki I did notice one area that could use some more details/explanation.  I have done some work with the Arduino IDE and the ESP8266 but I would not consider myself an expert by any means.  The one part I see people (in the project Issues) and myself initially is the part that states:

    "Verify source and upload once to sonoff using the serial connection..."

This line basically reads, "Complie and Upload", with little detail.  It might be useful to explain for newbies that they must: 

- Load the `portable/sketchbook/sonoff/sonoff.ino` into the IDE.  Now they can verify (or compile)  the project
- Then to upload they need to first hold the button on the SONOFF, power on the FTDI, release the button and NOW they can upload the firmware. (I realize not all products have a button, but the concept still remains the same).

I realize for seasoned users these steps may seem intuitive but for people new to the SONOFF, ESP8266, or Arduino IDE it may not be as apparent.  This is just a simple suggestion to possibly improve the Wiki a little.  Again, thanks for all the hard work.

**Comment by arendst** [comment]
Updated the wiki with your suggestions
