### ISSUE TITLE
Feature Request: Add support for NodeMCU. 

### ISSUE THREAD

**Issue by gizmochief7** [arendst/Sonoff-MQTT-OTA-Arduino#267]
I was hoping to reuse your library for testing on a NodeMCU and just connect up relays, leds, and/or reset buttons as needed depending on what type of Sonoff device i was trying to simulate. Your code compiled and pushed to the NodeMCU without any errors. I was able to hit the web server and toggle on and off the device with feedback in both the logs and the led status. However, I was not able to get any of the relay pins to actually trigger nor get the hardware button presses to fire an event to the logs or led.

**Comment by arendst** [comment]
If you execute command ```model 0``` things might change for the good as the software currently probably thinks it's a dual.

I suggest you use the next_gen version as there you have more control over the specific modules supported and could even update the sonoff_template.h file with your specific hardware configuration.

**Comment by jesusvallejo** [comment]
Ive tried the code on an nodemcu v1 and works just fine

**Comment by gizmochief7** [comment]
Yep, everything now works fully after running the model 1 command. You were right that it was thinking it was a Sonoff Dual at first. Thanks for the help and keep up the great work.
