### ISSUE TITLE
Compile issue when USE_MQTT disable and USE_WALL_SWITCH enabled

### ISSUE THREAD

**Issue by alphalove** [arendst/Sonoff-MQTT-OTA-Arduino#269]
Hello Arendst,
Just noticed a compile issue (in v3.2.8) when you disable USE_MQTT and enable USE_WALL_SWITCH.

The first error is on line 2514 of sonoff.ino, as there needs to be a conditional USE_MQTT compile around the use of 'mqttClient'... But once you put that in I get an error saying _addLog_P was not declared in this scope_.  That one I can't seem to work out as the function seems fine in support.ino. 

Thanks again for such a great (and fast moving!) project.

Kind regards,

alex

**Comment by arendst** [comment]
Fixed in version 3.2.9 just released
