### ISSUE TITLE
DS18B20 on gpio 14?

### ISSUE THREAD

**Issue by farhanito** [arendst/Sonoff-MQTT-OTA-Arduino#27]
can i modify the user_config.h so that i can use GPIO14 for DS18B20?

thanks

**Comment by arendst** [comment]
There is no problem in making your suggested changes. The whole idea of moving these config items into user_config.h is flexibility for you, the user.

If you're not using DHT22 I would suggest to change that GPIO to 4 so just swap the two.

Rgrds, Theo.

**Comment by farhanito** [comment]
Excellent. Thanks Theo
