### ISSUE TITLE
*Question* - Understanding Switch Modes

### ISSUE THREAD

**Issue by mrjemson** [arendst/Sonoff-MQTT-OTA-Arduino#276]
I can't find any documentation on the different Switch Modes and would like to get an understanding of what they each mean.

TOGGLE, FOLLOW, FOLLOW_INV, PUSHBUTTON or PUSHBUTTON_INV

I would have thought Toggle would allow you to use a normal latching wall switch and would toggle based on state change, but that doesn't seem to be the case in my testing.
As such I would like to get an understanding of what each mode *should* do, so I can correctly raise an issue if it is in fact misbehaving.

**Comment by arendst** [comment]
See Wiki - Commands all the way down...

**Comment by mrjemson** [comment]
Thanks. I have it set to toggle, but it seems to be behaving like push button.
I will do some further testing to confirm and come back.
