### ISSUE TITLE
MQTT_MAX_PACKET_SIZE cannot be set in  PubSubClient.h no such file!

### ISSUE THREAD

**Issue by hoekbrwr** [arendst/Sonoff-MQTT-OTA-Arduino#278]
I have copied the sonoff directory into the sketch directory compiled and loaded the firmware.
Now I get this warning to set MQTT_MAX_PACKET_SIZE to at least 300, but with the Arduino there is no such file. Why not defining it to that value by default?

**Comment by marcelveldt** [comment]
look in the libraries folder of your sketch directory, there should be a folder named pubsubclient

**Comment by hoekbrwr** [comment]
Thx. I got it! I is in the Arduin/Projects/libraries, not in the sonoff sketch directory.
