### ISSUE TITLE
small typo in code

### ISSUE THREAD

**Issue by marcelveldt** [arendst/Sonoff-MQTT-OTA-Arduino#284]
There seems to be a small typo in the code for the next_gen version.
In case you didn't notice it yet:

Usage of DHT is defined with USE_DHT1 or USE_DHT2 (in user_config.h)

The code is however checking for USE_DHT instead of USE_DHT1

**Comment by arendst** [comment]
Thnx. Will be fixed in next release.

**Comment by arendst** [comment]
Not a release but just fixed in current version
