### ISSUE TITLE
next_gen/sonoff - Sonoff Dual Relais is not switching

### ISSUE THREAD

**Issue by thommycgn** [arendst/Sonoff-MQTT-OTA-Arduino#287]
I tested now next_gen/sonoff on Sonoff Basic & Sonoff  Dual. 

With the Sonoff Dual: If I toggle the status it's changing on the webinterface, but the Relais is not reacting. Of course I selected the Sonoff Dual Module.

**Comment by arendst** [comment]
Known issue

**Comment by arendst** [comment]
Fixed in version 3.9.4 just released
