### ISSUE TITLE
bug: wemo_emulation on Sonoff Dual

### ISSUE THREAD

**Issue by thommycgn** [arendst/Sonoff-MQTT-OTA-Arduino#288]
Hi! 

In configuration I was set friendly_name1 +2 but only friendly_name1 is recognized by Alexa. The Second Device is not shown.

**Comment by altelch** [comment]
Hi,

switch Serial or Console Debug du 4 DEBUG MORE and check the log for Response1/2/3 messages and HUE Bridge Configuration messages. The code was testet with up to 4 devices and worked. You can also call http://<yoursonoffip>/api/doesntmatter/lights to see the xml returned to the Echo. There should be the 2 friendly names.

**Comment by arendst** [comment]
For clarity, Wemo emulation only supports 1 device and Hue emulation supports up to 4 devices?

**Comment by altelch** [comment]
Hi,

exactly. Wemo supports only one device. The HUE code is limited by 
Maxdevices. Should there ever be a Sonoff device with more channels they 
will be supported.


Greetings,


     Heiko.


Am 28.01.2017 um 12:08 schrieb Theo Arends:
