### ISSUE TITLE
4CH

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-MQTT-OTA-Arduino#295]
Hi

Just wondering if anyone had issues with the 4CH? I've used this software on many of my Sonoffs no problem - but yesterday I programmed a Sonoff 4CH v1.1 - all looked ok, I had selected MODULE SONOFF_2 - and it looked like it programmed but thereafter - nothing... no serial, no flashing lights etc... the only thing that comes to mind is I can't see any FLASH so possibly NOT an ESP8266 but the new cheap ESP8255 - should not make any difference?

**Comment by jaysuk** [comment]
They use the ESP8265

**Comment by scargill** [comment]
Am I right in saying that should be set up in the Arduino environment as an 8266 with 1 MEG? Didn't work...

**Comment by jaysuk** [comment]
No. Should have an option for generic esp8265 with 1 meg

**Comment by scargill** [comment]
It did - and that worked - thanks - http://tech.scargill.net/sonoff-4ch-4-channel-mains-control/
