### ISSUE TITLE
DHT22

### ISSUE THREAD

**Issue by maxjenius** [arendst/Sonoff-MQTT-OTA-Arduino#3]
Hello, thank you so much for your work!  I have a Sonoff TH board and was wondering if you were going to add DHT22 capabilities to the code any time in the future.  Just wondering, thanks again!

**Comment by arendst** [comment]
I have no plans to implement the DHT code but feel free to do so yourself ;-)

**Comment by maxjenius** [comment]
OK, just wondering, thanks!
