### ISSUE TITLE
Can DHT21/AM2301 works on Sonoff POW?

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-MQTT-OTA-Arduino#301]
I found some people connect sensor on Sonoff Basic, so is it possible to connect to Sonoff POW (I mean connect to the serial interface)? and retrieve all info in one piece? I am planning to use POW as a power meter and attach to some device and power bar and check the daily usage on power, if  AM2301 can attach on it, that would be awesome, it will make environment checking be perfect.

**Comment by arendst** [comment]
I do not support it as the signal pins are connected to the AC wires. I wish you luck and rubber hands...

**Comment by hamwong** [comment]
how about connector to serial pin? as the 3.3 tx and GND pin?
as after flash you firmware, upgrade only by OTA.
