### ISSUE TITLE
Support for new sonoff device

### ISSUE THREAD

**Issue by nigelb135** [arendst/Sonoff-MQTT-OTA-Arduino#31]
Your continued pace of development with this software is impressive, and welcomed.

Just wondering if you are planning to support the new Sonoff board DC 5V-24V DIY WIFI Wireless Switch Sonoff SV Module For Smart Home? I've got one on order and will see if it works when I get it in a week or so.

One possible use is to control a garage door -- so I'm guessing that I'm going to need a push-button type output.

Thanks again for sharing - I've used v1.30 to connect 9 lights to my Home Assistant setup in a Pi.

**Comment by arendst** [comment]
Should work. If not just let me know.

**Comment by nigelb135** [comment]
Sounds good. I'll let you know how it goes. Nigel
