### ISSUE TITLE
BMP180 doesn't show pressure in Domoticz

### ISSUE THREAD

**Issue by asimmetrico** [arendst/Sonoff-MQTT-OTA-Arduino#328]
Hello,
I really don't know if this is an issue with Tasmota or Domoticz.
I connected a BMP180 to Itead Sonoff dev.
The config webpage shows values for both temperature and pressure correctly. It connects with mosquitto and this is what I get
2017-11-04 09:11:20.021 MQTT: Topic: domoticz/in, Message {"idx":4,"nvalue":0,"svalue":"19.9;0.0;0;979.9;5"}
It looks correct to me but Domotics read the device as BMP085 and shows correctly the temperature but not the pressure. This is what I get from Domoticz
Dummy	14054	1	Temp BMP	Temp + Baro	BMP085 I2C	19.9 C, 0.0 hPa	-	-
I suppose that Domoticz expect the pressure value in a different order in the string or ?

Can you help me to get the pressure?

Thanks

Al

**Comment by arendst** [comment]
Next time open an issue in repository Sonoff-Tasmota please.

I configured a TempHumBaro sensor in Domoticz:
![image](https://user-images.githubusercontent.com/11044339/32505225-f3d53ef0-c3e1-11e7-9cbc-ea45e350850e.png)

and fed the index to tasmota device:
![image](https://user-images.githubusercontent.com/11044339/32505248-09663d32-c3e2-11e7-91e3-b80d425afd7a.png)

resulting in this:
![image](https://user-images.githubusercontent.com/11044339/32505301-2399f2ac-c3e2-11e7-9b53-9b81082e32bf.png)

Works fine with me...

**Comment by asimmetrico** [comment]
Yes the config. is similar to mine. But with the BMP180 doesn't work for me.
Is it there an easy way to change the position of the pressure value in the Mqtt string?
Could you please show your Mqtt string from Domoticz log? Is it similar to mine?

I apologize for the post. I supposed this was he correct place.

Thanks

Alberto

**Comment by asimmetrico** [comment]
Uhm, I get a difference. You used a temp/hum/baro and not temp/baro. This may make a difference. Let me try.

Thanks a lot

Al

**Comment by asimmetrico** [comment]
It works this way
Thanks

Al
