### ISSUE TITLE
Itead S20 and pictures

### ISSUE THREAD

**Issue by ThomDietrich** [arendst/Sonoff-MQTT-OTA-Arduino#37]
Hey arendst,
just wanted to tell you, that you may add [Itead S20 socket](https://www.itead.cc/smart-home/smart-socket-eu.html) to your list of supported devices. Just flashed it just like the Sonoff and everything works as expected.

Also, I have posted two pictures of the flashing process. Feel free to copy them to your wiki, maybe as an replacement to the unclear diagram... 😃 https://community.openhab.org/t/itead-switches-and-sockets-cheap-esp8266-wifi-mqtt-hardware/15024/2

**Comment by arendst** [comment]
Thanks for the information. I've update both the code and the wiki.
