### ISSUE TITLE
Do yo plan support Sonoff Pow ?

### ISSUE THREAD

**Issue by Lstt2005** [arendst/Sonoff-MQTT-OTA-Arduino#44]
Dear friends! Do you plan support Sonoff Pow - https://www.itead.cc/wiki/Sonoff_Pow (device’s immediate wattage consumption or kWh energy usage over a period of time,).
Thank's.

**Comment by ThomDietrich** [comment]
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/issues/38

**Comment by Lstt2005** [comment]
Thanks!
