### ISSUE TITLE
WKaku 10k resistor

### ISSUE THREAD

**Issue by simoneberchielli** [arendst/Sonoff-MQTT-OTA-Arduino#52]
Hello, I was looking at WKaku schematics and I noticed 10k resistor for GPIO15 is missing. What' s the purpose of that resistor?

Great project! I'm using it on my SONOFF and works perfectly with Home Assistant

**Comment by arendst** [comment]
The 10k R keeps GPIO15 low during restart so the esp8266 doesn't start in update mode. See esp8266 datasheets.

In wkaku you'll need to use the R between GPIO15 and the PCA. Also see my wiki.

**Comment by simoneberchielli** [comment]
Thank you for reply, I checked both documents. I built WKaku on breadboard but I'm having some issues. I'm using an ESP-12F module with all memory erased, v2.0.6 of your project and Arduino IDE 1.6.12. I managed to upload FW by pressing button and browsing web server for configuration. Led working also. But board is recognized as Sonoff Dual, button and relay don't work. I checked all connections, I cannot figure out what i'm doing wrong

**Comment by arendst** [comment]
During initial power up I'm testing for Sonoff or Sonoff dual by checking pin GPIO12 where the sonoff has  a relay connected with resistors to Gnd. The Sonoff Dual does not.

In your case this test fails and it selects Sonoff Dual.

I was expecting this and implemented a command to easily overcome this. Try command ```model 1```. This should solve your problem.

**Comment by simoneberchielli** [comment]
`model 1` in command console makes it working, thanks! I tryied also `model 2` to get back to Dual. In case of Dual, what's GPIO configuration to use 2 relays? In previous release (2.0.5) there were some specific parameters in user_config.h as I remember. Do you remove from 2.0.6?

**Comment by arendst** [comment]
Dual does not use GPIO for relays. It has a dedicated chip connected to the serial interface using serial commands to switch relais. See Sonoff Dual schematics.

**Comment by simoneberchielli** [comment]
I saw the PSB schematic and I found piece of code where serial commands are sent. Sorry for my noobish questions but I'm new to your project and I would have more time to read all code. Thank you!
