### ISSUE TITLE
Open Wiki for user changes

### ISSUE THREAD

**Issue by ThomDietrich** [arendst/Sonoff-MQTT-OTA-Arduino#68]
Another issue I created here was taken hostage by users not able to make sense out of the wiki documentation. I have to agree, it is not perfect - but contains all information you need.

In my personal experience people will contribute to the wiki of a project if it is open for changes by users. You should consider that.

**Comment by arendst** [comment]
Just opened up for everyone...

**Comment by ThomDietrich** [comment]
Wonderful!

**Comment by ThomDietrich** [comment]
@Toshibass @patrickruijters @roadfox @jumpjack @patbeirne
