### ISSUE TITLE
Newbie tutorial for upgrading Sonoff Pow firmware

### ISSUE THREAD

**Issue by jumpjack** [arendst/Sonoff-MQTT-OTA-Arduino#69]
I am attempting to write a step by step  tutorial about how to upgrade the Sonoff Pow firmware, but I'm in trouble figuring out the exact steps...
[https://jumpjack.wordpress.com/2016/11/08/arduino-esp8266-sonoff-e-mqtt/](https://jumpjack.wordpress.com/2016/11/08/arduino-esp8266-sonoff-e-mqtt/)

**Comment by arendst** [comment]
See wiki

**Comment by jumpjack** [comment]
wiki is far from beeing useful for newbies.
