### ISSUE TITLE
Upload image problem

### ISSUE THREAD

**Issue by littlebilly** [arendst/Sonoff-MQTT-OTA-Arduino#76]
Upload image with sonoffs web server and upload the file directly is not possible.
I always get "Upload failed --> Upload error code 5" sometimes "Upload failed --> Upload error code 7"
Equal using Chrome or IE Browser.

Do you have an idea?
Billy

**Comment by arendst** [comment]
5 = upload write buffer miscompare
7 = upload abort

Make sure sonoff has a good wifi connection and you used the correst SPIFFS size 64k

**Comment by littlebilly** [comment]
Thanks a lot for your hints.
Everything is working now!
Spiffs was ok but not th Flash Size. (512k was wrong)
