### ISSUE TITLE
OTA improvements

### ISSUE THREAD

**Issue by wiktorschmidt** [arendst/Sonoff-MQTT-OTA-Arduino#83]
Hey Theo,

First of all - thanks for creating this piece of software - amazing upgrade over the original Sonoff software platform.

Following a quick discussion here:
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/pull/80#issuecomment-260179975

Here are some ideas on how to automate the OTA over multiple devices:
http://blog.squix.org/2016/06/esp8266-continuous-delivery-pipeline-push-to-production.html
https://ptarmiganlabs.com/blog/2016/02/23/esp8266-over-the-air-updating-what-are-the-options/
https://www.penninkhof.com/2015/12/1610-over-the-air-esp8266-programming-using-platformio/
https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.md#http-server

It looks like you are using ESP8266httpUpdate in parts of the code.

I'm not exactly sure what's the best way to integrate this with PlatformIO and/or Github releases.

I think the ideal scenario would be if one can set something like "https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/releases/latest/firmware.bin" as OTAURL and use MQTT to trigger upgrade #holygrail ;)

Just putting it out there for discussion.

**Comment by arendst** [comment]
The last option would be fine as long as there was only one compiled version needed. In practice many people change values in user_config.h to delete or add features (not) needed and they are supposed to do that.

I'm also a strong believer of keeping the internet out of my Home Automation environment as that was the reason to write this software in the first place. So keep your firmware on your intranet hosted by your own webserver and execute command ```cmnd/sonoffs/upgrade 1``` to upgrade all sonoffs at once using the MQTT GroupTopic.

The links containing information about automating OTA are informative but currently I do not plan to change the current "simple" OTA implementation as it still supports the internet option too.

My remark regarding PlatformIO support was more geared towards having a script to move the compiled firmware.bin file to your local webserver to allow the current sonoff software to use the same process for group updating as it has with the Arduino IDE using my adjustments.

Also keep in mind that the core task of this software is switching relays using MQTT ;-)
