### ISSUE TITLE
Power vs. Energy

### ISSUE THREAD

**Issue by dagbdagb** [arendst/Sonoff-MQTT-OTA-Arduino#91]
Hopefully this isn't considered "pedantic".

"Total Power Today 0.000 kWh" is... flat out wrong. 

Ditto:

tele/sonoff/TODAY_POWER 0.001 kWh
tele/sonoff/PERIOD_POWER 0 Wh

Power is commonly expressed with the unit Watt, but Wh is used for *energy*. The two are not interchangeable.

**Comment by arendst** [comment]
You're right. I'll correct in next release. Glad you started of with pedantic...

**Comment by arendst** [comment]
Implemented in version 2.0.15
