### ISSUE TITLE
messageformat

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-MQTT-OTA-Arduino#94]
Erm, I selected messageformat 1

Didn't seem to do much - the messages look the same

**Comment by arendst** [comment]
It currently only supports status messages (ie ```status 4```).

**Comment by arendst** [comment]
Now all telemetry data can be returned in JSON format.

**Comment by TotallyInformation** [comment]
Can that be made a default by adjusting the user_config.h file?

It would fit in with my configuration much better.

**Comment by arendst** [comment]
I will implement this but keep in mind that it will only work once as changes to user_config.h will by default not change any STORED values in flash.

By changing the value of  CFG_HOLDER flash will be reinitialized with default values from user_config.h

**Comment by TotallyInformation** [comment]
Thanks. That's fine as I would just prefer to be able to set it as the default for new devices.

**Comment by arendst** [comment]
Implemented in version 2.0.17 just released

**Comment by TotallyInformation** [comment]
Thanks.

**Comment by arendst** [comment]
Version 3.0.0 supports full JSON messages.
