### ISSUE TITLE
Operating Sonoff S20 (newbie)

### ISSUE THREAD

**Issue by JoeWiseman** [arendst/Sonoff-MQTT-OTA-Arduino#96]
Hi there,
I want want to use the Sonoff S20 along with my smartphone (without a china-app) and my home automation system (no MQTT-support!).

So I like to ask if it is possible to send http-, tcp- or udp-commands with your firmare, so that I will be able to switch on / off, toggle (and maybe get the status) through this commands?

I would be very  thankful if you give answer my question.

Reragds 
Joe

**Comment by arendst** [comment]
See #89
